### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [teambtcmap/btcmap-android#27]
I use the fdroid flavor but I got 

```
Task 'assembleFdroidRelease' not found in project ':app'.
```

Could you please take a look? Thanks!

**Comment by bubelov** [comment]
I had to switch to build flavors due to https://github.com/cashapp/sqldelight/issues/3584

Checked the F-Droid meta and it looks like it was already reconfigured by @licaon-kter so let's keep this issue open and see if the next build succeeds.

@linsui if you're comfortable with building things directly, try:

```
./gradlew clean assFdroidSelfSignedRelease
```

Please note that self-signed builds are less safe so you can only trust them if you build them yourself. F-Droid uses its own private key so those builds are trusted.

**Comment by linsui** [comment]
Finally I patched the code and removed the `signingConfig` to build an unsigned apk. What's the expected way to build an unsigned apk? As you said, F-Droid signs apks with its own key so we need an unsigned apk.

**Comment by bubelov** [comment]
> Finally I patched the code and removed the `signingConfig` to build an unsigned apk. What's the expected way to build an unsigned apk? As you said, F-Droid signs apks with its own key so we need an unsigned apk.

This line strips the built-in sig: https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/org.btcmap.yml#L173

**Comment by bubelov** [comment]
I'm surprised that it requires unsigned APKs since replacing the signature should be trivial, but those are unimportant details.

**Comment by bubelov** [comment]
I can probably add an `unsigned` flavor but I think the current setup should work just fine.

**Comment by linsui** [comment]
Maybe fdroidserver can just re-sign the apk. I'm not sure. Anyway, it builds fine with the patch. So I thought it's OK. Thanks!
